site_name: Youth Justice Nav
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - footnotes
    - navigation.top
    - toc.follow
    - navigation.path
    - toc.integrate
plugins:
    - search
    - awesome-pages
nav:
  - Home: docs/index.md
  - Help Me: docs/Help-Me/index.md
  - Resources: docs/Resources/index.md
  - About Us: docs/About-Us/index.md
