site_name: Youth Justice Nav
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - footnotes
    - navigation.top
    - toc.follow
    - navigation.path
    - toc.integrate
plugins:
    - search
    - awesome-pages
nav:
    - Home: index.md
    - Help Me: Help-Me/index.md
    - Resources: Resources/index.md
    - About Us: About-Us/index.md
