---
hide:
  - navigation
---
site_name: Youth Justice Nav
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - footnotes
    - navigation.top
    - toc.follow
    - navigation.path
